### ISSUE TITLE
Add custom folders during paketo build

### ISSUE THREAD

**Issue by goafabric** [paketo-buildpacks/base-builder#484]
I am using paketo build packs with Spring Boot for Native Container Images + Maven.
And because of some limitations of flyway, I have the requirement to add an additional directory with content to the image.
JIb has a property "extraDirectories" to achieve this.
But diving into paketos documentation i could not find something similar.
So is there something  that can be activated by some <BP_XX> Parameter ?

Otherwise i have to leverage JIB or a Dockerfile afterwards

Thank you in advance

**Comment by fg-j** [comment]
This sounds like an issue related to the Java buildpack cleaning up directories. Transferring to the java-native-image buildpack repo.

**Comment by goafabric** [comment]
will do, thx .. it's a little confusing honestly where to raise the question 
coming from spring boot

**Comment by goafabric** [comment]
https://github.com/paketo-buildpacks/java/issues/662

you may close this issue than

**Comment by fg-j** [comment]
@goafabric Totally understandable! Paketo maintainers are always happy to route you to the best people to answer your questions 🙂
