### ISSUE TITLE
Base Builder should get published to official Dockerhub AND GCR locations

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/base-builder#5]
**Context**
Once we've implemented https://github.com/paketo-buildpacks/builder/issues/31 and https://github.com/paketo-buildpacks/builder/issues/32, **and** we've verified that the changes look good, we should swap over from the temporary GCR path to the **official** Dockerhub **and** location for the Base Builder.

Builders should get published to the following location:
`paketobuildpacks/builder:base` (for the latest version)
`paketobuildpacks/builder:<VERSION>-base` (for specific versions)
`gcr.io/paketo-buildpacks/builder:base` (for the latest version)
`gcr.io/paketo-buildpacks/builder:<VERSION>-base` (for the latest version)
`cloudfoundry/cnb:base` (for the latest version)
`cloudfoundry/cnb:<VERSION>-base` (for specific versions)

**Notes** 
- This is a little different from the Full builder work. For backwards compatibility reasons, we'll have to continue publishing Base Builder to both GCR and Dockerhub
- At this point, we can get rid of the Concourse jobs for the Base builder.

**Comment by floragj** [comment]
The base builder should also be published to `paketobuildpacks/builder:base` as per [this RFC](https://github.com/paketo-buildpacks/builder/blob/main/rfcs/0004-base-builder-is-latest.md).
