### ISSUE TITLE
Memory issue with base-builder 0.3.207

### ISSUE THREAD

**Issue by alexisparis** [paketo-buildpacks/base-builder#773]
Hello,
We switched from base-builder version 0.3.182 to 0.3.207 to build docker images for a spring-boot project (using the spring-boot maven plugin to interact with Paketo Buildpacks) and faced some regressions regarding memory. 
The considered project is a webflux spring boot 2.7.9 project and we use https://github.com/paketo-buildpacks/datadog to enable datadog monitoring of this api.
We used the produced Docker image to deploy this api on AWS EKS.

When using 0.3.207, we can see that the total memory used by the container gradually increases until it reaches the maximum memory available and pods begin restarting.

<img width="1413" alt="image" src="https://user-images.githubusercontent.com/462120/233104141-5605c8f9-8abb-4fc5-a562-704a924d8934.png">

The amount of heap and non heap memory appears to be quite stable :

<img width="1545" alt="image" src="https://user-images.githubusercontent.com/462120/233104767-00680bd4-39a4-439b-b3b4-4a37e836666c.png">

With builder 0.3.182, the evolution of the memory used by the container is more linear :

<img width="1405" alt="image" src="https://user-images.githubusercontent.com/462120/233105160-0d8278a1-1a7b-4101-ad41-93e45256c4cb.png">

We try to analyze the differences between the two versions of the builder and it seems that amongst several upgrades of inner components, one of the main change is the switch from the datadog agent 1.6.0 to 1.10.0.

We also realize that there is an issue opened on https://github.com/DataDog/dd-trace-java, https://github.com/DataDog/dd-trace-java/issues/4883 which seems to be related to our issue.
Datadog also released the version 1.12.1 few days ago.

Is there any known regressions between those 2 versions?
From your point of view, could those memory issues be related to the Java datadog agent?
If the memory issue is related to datadog agent, is it planned to use the new 1.12.1?
Thank you in advance for you help.

**Comment by robdimsdale** [comment]
cc @paketo-buildpacks/java-maintainers @paketo-buildpacks/utilities-maintainers

**Comment by alexisparis** [comment]
Thanks for the quick release @dmikusa 

We have made load tests with datadog disabled and the memory was quite stable (load test duration : 5 hours).
We have also tested with base-builder 0.3.219 and the buildpack paketo 3.8.0 (https://github.com/paketo-buildpacks/datadog/releases/tag/v3.8.0), performed a load test during several hours and, also in this case, no memory leak issue :

<img width="1404" alt="image" src="https://user-images.githubusercontent.com/462120/233521078-ff52633f-cd1c-47c8-8f67-1673c52c9b88.png">

**Comment by dmikusa** [comment]
That's good. It sounds like whatever issue you were hitting has been fixed in the Datadog agent.

We try to keep up-to-date with the Datadog agent, but if you ever notice us lagging behind or have specific questions about when a version will be available feel free to open an issue against the repo: https://github.com/paketo-buildpacks/datadog/issues.

**Comment by robdimsdale** [comment]
It sounds like we got to a satisfactory solution, so I'm going to close this issue. Feel free to re-open if you see this again.
